import React from 'react'
import { NavBar } from '../NavBar'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../../../styles/Home.module.css'
import style from "../compnents.module.css"
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export const MainLayout = ({ children }) => {
    return (
        <div className={style.menu}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <NavBar />
                {children}
                <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
            </main>
        </div>
    )
}
